version: '3.9'

services:
  health-check-app:
    container_name: health-check-app
    image: health-check-app:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file: .env
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/
    restart: unless-stopped
  grpc-server-app:
    container_name: grpc-server-app
    image: grpc-server-app:1.0
    build:
      context: .
      dockerfile: ./grpc-server/Dockerfile
    ports:
      - '50051:50051'
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    networks:
      - app-network
  redis:
    container_name: test-redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:

volumes:
  postgres-data:
  